Product.create!([
  {name: "Opt-Tech Elite 5", price: 50000, image_url: "https://www.venturacountylasik.com/wp-content/uploads/woman-with-a-bionic-eye.jpg", description: "Optical enhancements with V5 software, thermal upgrade, mini-jack retracer port, HueShift, Sec-ACCEL enhancement"},
  {name: nil, price: 200, image_url: nil, description: nil},
  {name: "HoV-R Boots", price: 156000, image_url: "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F3821c0f6-bd9d-4108-8529-056ef571760d_1000x562.jpeg", description: "A pair of black and chrome thruster boots, lightweight frames, water/sludge resistant, g7X-flight chip, accelerator module V"},
  {name: "MorphSuit", price: 200000, image_url: "https://www.morphsuits.com/media/catalog/product/cache/937f440085cd52c4f06eb785557b6967/m/1/m1_m_p_mpinf_1.jpg", description: "Breathable, formable to any size, easy to program, H3 hardware, mini-jack port, Sec-URE Chip"},
  {name: "JackrunnerZ", price: 6000, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYys-4Ft1xZAl0WN8_bEAXdNY1ND__AcD95g&usqp=CAU", description: "Stylish, lightweight, water/sludge resistant, accelerator module with control"},
  {name: "HueShift Pants", price: 18000, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUbxnLtftnKccM3u9QDoscZRNj3G-7msou61s2f7pQWERoznmB1LRwNm1WSr1kLj2YWvs&usqp=CAU", description: "Stylish, integrated f6 chip, chameleon and pattern modes, formable to any size, mini-jack RGB port, HueShift v5"},
  {name: "ThermJac Jacket", price: 10000, image_url: "https://preview.redd.it/a-thermal-camouflage-jacket-with-42-graphene-patches-and-v0-tbqkkgofozha1.jpg?width=640&crop=smart&auto=webp&s=b9970bb8b343f64e2b465c7c36e868c8dfcae807", description: "Therm-Invis Jacket, formable to any size, mini-jack port, HueShift, Sec-ACCEL & Sec-URE chip"}
])
