json.created_at product.created_at
json.id product.id
json.price product.price
json.description product.description
json.name product.name
json.is_discounted? product.is_discounted?
json.tax product.tax
json.total product.total
json.quantity product.quantity
json.supplier product.supplier
json.images product.images
json.categories product.categories